/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ABMInventario.java
 *
 * Created on 06/08/2013, 15:21:59
 */

package gui.inventario;

import crm.client.managers.DepositosManager;
import crm.client.managers.EquiposFamiliasManager;
import crm.client.managers.EquiposManager;
import crm.libraries.abm.entities.Depositos;
import crm.libraries.abm.entities.Equipos;
import crm.libraries.abm.entities.EquiposFamilias;
import gui.inventario.componentes.FamiliasComboBox;
import gui.tables.BusquedaEquiposTableModel;

import java.awt.Color;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.print.Doc;
import javax.print.DocFlavor;
import javax.print.DocPrintJob;
import javax.print.PrintException;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.print.SimpleDoc;
/**
 *
 * @author saciar
 */
public class ABMInventario extends javax.swing.JDialog {

    /** Creates new form ABMInventario */
    public ABMInventario(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarItemsComboBoxfamilias();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nuevoNombreTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nuevoFamiliaCmb = new FamiliasComboBox();
        jLabel4 = new javax.swing.JLabel();
        nuevoSerialTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        nuevoObservacionesTxt = new javax.swing.JTextArea();
        nuevoGuardarBtn = new javax.swing.JButton();
        nuevoCancelarBtn = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        nuevoDepositoCmb = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        nuevoModeloTxt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        nuevoPesoTxt = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        nuevoAltoTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nuevoAnchoTxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        nuevoLargoTxt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        modNombreTxt = new javax.swing.JTextField();
        modFamiliaCmb = new FamiliasComboBox();        
        modSerialTxt = new javax.swing.JTextField();
        modCodigoTxt = new javax.swing.JTextField();
        modBuscarBtn = new javax.swing.JButton();
        modGuardarBtn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        modCancelarrBtn = new javax.swing.JButton();
        modDepositoCmb = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        modModeloTxt = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        modAltoTxt = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        modAnchoTxt = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        modLargoTxt = new javax.swing.JTextField();
        modPesoTxt = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        modObservacionTxt = new javax.swing.JTextArea();
        modMarcaRad = new javax.swing.JRadioButton();
        modFamiliaRad = new javax.swing.JRadioButton();
        modNroSerieRad = new javax.swing.JRadioButton();
        modCodBarraRad = new javax.swing.JRadioButton();
        modDepositoRad = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 768));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Alta baja y modificacion del inventario");

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel2.setText("Marca");

        jLabel3.setText("Familia");

        jLabel4.setText("Nro de serie");

        jLabel6.setText("Observaciones");

        nuevoObservacionesTxt.setColumns(20);
        nuevoObservacionesTxt.setRows(5);
        jScrollPane1.setViewportView(nuevoObservacionesTxt);

        nuevoGuardarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crm/gui/imagenes/disk.png"))); // NOI18N
        nuevoGuardarBtn.setText("Guardar");
        nuevoGuardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoGuardarBtnActionPerformed(evt);
            }
        });

        nuevoCancelarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crm/gui/imagenes/textfield.png"))); // NOI18N
        nuevoCancelarBtn.setText("Limpiar");
        nuevoCancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoCancelarBtnActionPerformed(evt);
            }
        });

        jLabel17.setText("Deposito");

        jLabel12.setText("Modelo");

        jLabel16.setText("Peso");

        nuevoPesoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoPesoTxtActionPerformed(evt);
            }
        });

        jLabel19.setText("Kgs");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dimensiones (En cm)"));

        jLabel14.setText("Alto");

        nuevoAltoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoAltoTxtActionPerformed(evt);
            }
        });

        jLabel5.setText("Ancho");

        nuevoAnchoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoAnchoTxtActionPerformed(evt);
            }
        });

        jLabel15.setText("Largo");

        nuevoLargoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoLargoTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nuevoAltoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nuevoAnchoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nuevoLargoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(nuevoAltoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(nuevoAnchoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(nuevoLargoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nuevoFamiliaCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nuevoSerialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nuevoDepositoCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 207, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nuevoNombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nuevoModeloTxt))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(271, 271, 271)
                                .addComponent(nuevoGuardarBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nuevoCancelarBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nuevoPesoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nuevoNombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(nuevoModeloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nuevoFamiliaCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nuevoSerialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(nuevoDepositoCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(nuevoPesoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoGuardarBtn)
                    .addComponent(nuevoCancelarBtn))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Alta", jPanel1);

        modFamiliaCmb.setEnabled(false);

        modSerialTxt.setEnabled(false);

        modCodigoTxt.setEnabled(false);
        modCodigoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modCodigoTxtActionPerformed(evt);
            }
        });
        modCodigoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                modCodigoTxtKeyPressed(evt);
            }
        });

        modBuscarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crm/gui/imagenes/magnifier.png"))); // NOI18N
        modBuscarBtn.setText("Buscar");
        modBuscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modBuscarBtnActionPerformed(evt);
            }
        });

        modGuardarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crm/gui/imagenes/disk.png"))); // NOI18N
        modGuardarBtn.setText("Guardar");
        modGuardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modGuardarBtnActionPerformed(evt);
            }
        });

        jTable1.setModel(new BusquedaEquiposTableModel());
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable1);

        modCancelarrBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crm/gui/imagenes/textfield.png"))); // NOI18N
        modCancelarrBtn.setText("Limpiar");
        modCancelarrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modCancelarrBtnActionPerformed(evt);
            }
        });

        modDepositoCmb.setEnabled(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imagenes/delete.png"))); // NOI18N
        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel13.setText("Modelo");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Dimensiones (En cm)"));

        jLabel20.setText("Alto");

        modAltoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modAltoTxtActionPerformed(evt);
            }
        });

        jLabel21.setText("Ancho");

        modAnchoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modAnchoTxtActionPerformed(evt);
            }
        });

        jLabel22.setText("Largo");

        modLargoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modLargoTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modAltoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modAnchoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modLargoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(modAltoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(modAnchoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(modLargoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        modPesoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modPesoTxtActionPerformed(evt);
            }
        });

        jLabel23.setText("Peso");

        jLabel24.setText("Kgs");

        jLabel11.setText("Observaciones");

        modObservacionTxt.setColumns(20);
        modObservacionTxt.setRows(5);
        jScrollPane2.setViewportView(modObservacionTxt);

        buttonGroup1.add(modMarcaRad);
        modMarcaRad.setSelected(true);
        modMarcaRad.setText("Marca");
        modMarcaRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modMarcaRadActionPerformed(evt);
            }
        });

        buttonGroup1.add(modFamiliaRad);
        modFamiliaRad.setText("Familia");
        modFamiliaRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modFamiliaRadActionPerformed(evt);
            }
        });

        buttonGroup1.add(modNroSerieRad);
        modNroSerieRad.setText("Nro de serie");
        modNroSerieRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modNroSerieRadActionPerformed(evt);
            }
        });

        buttonGroup1.add(modCodBarraRad);
        modCodBarraRad.setText("Codigo de barras");
        modCodBarraRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modCodBarraRadActionPerformed(evt);
            }
        });

        buttonGroup1.add(modDepositoRad);
        modDepositoRad.setText("Deposito");
        modDepositoRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modDepositoRadActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imagenes/printer.png"))); // NOI18N
        jButton2.setText("Reimprimir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(modMarcaRad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modNombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modModeloTxt))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(modFamiliaRad)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(modFamiliaCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(modCodBarraRad)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(modCodigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(modDepositoRad)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(modDepositoCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(modNroSerieRad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modSerialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addComponent(modBuscarBtn)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modPesoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2)))
                        .addGap(10, 10, 10))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(modGuardarBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modCancelarrBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modNombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(modModeloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modMarcaRad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modFamiliaCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modFamiliaRad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modSerialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modBuscarBtn)
                    .addComponent(modNroSerieRad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modCodigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modCodBarraRad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modDepositoCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modDepositoRad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(modPesoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modGuardarBtn)
                    .addComponent(modCancelarrBtn)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Modificacion y Baja", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(771, 602));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private String generateBars(){
        return "";
    }    
    
    private void nuevoGuardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoGuardarBtnActionPerformed
        // TODO add your handling code here:
        if(validarNuevo()){
            try {
                Equipos eq = new Equipos();
                eq.setEqDescripcion(nuevoNombreTxt.getText());
                eq.setModelo(nuevoModeloTxt.getText());
                if(!nuevoSerialTxt.getText().isEmpty())
                    eq.setEqNroserie(nuevoSerialTxt.getText());
                if(!nuevoObservacionesTxt.getText().isEmpty())
                    eq.setObservaciones(nuevoObservacionesTxt.getText());
                eq.setInvDepositos(((Depositos) nuevoDepositoCmb.getSelectedItem()).getCodigo());
                eq.setInvEquiposFamilias((nuevoFamiliaCmb.searchForeign()));
                eq.setEqActivo("S");
                eq.setCodigoBarras(generateBars());
                eq.setEqEstado("1");
                eq.setModelo(nuevoModeloTxt.getText());
                if(!nuevoAltoTxt.getText().isEmpty())
                    eq.setAlto(Integer.parseInt(nuevoAltoTxt.getText()));
                if(!nuevoAnchoTxt.getText().isEmpty())
                    eq.setAncho(Integer.parseInt(nuevoAnchoTxt.getText()));
                if(!nuevoLargoTxt.getText().isEmpty())
                    eq.setLargo(Integer.parseInt(nuevoLargoTxt.getText()));
                if(!nuevoPesoTxt.getText().isEmpty())
                    eq.setPeso(Integer.parseInt(nuevoPesoTxt.getText()));
                Equipos e = EquiposManager.instance().update(eq);
                JOptionPane.showMessageDialog(this, "Equipo guardado con exito!", "Guardado", JOptionPane.INFORMATION_MESSAGE);
                int res = JOptionPane.showConfirmDialog(this, "Desea imprimir la etiqueta con el codigo de barras?", "Imprimir", JOptionPane.YES_NO_OPTION );
                if(res == JOptionPane.YES_OPTION){
                    imprimirEtiqueta(e);
                }
                limpiarNuevo();
            } catch (RemoteException ex) {
                Logger.getLogger(ABMInventario.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Error al grabar el equipo", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_nuevoGuardarBtnActionPerformed

    private void modBuscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modBuscarBtnActionPerformed
        refreshTable();
    }//GEN-LAST:event_modBuscarBtnActionPerformed

    private void modCancelarrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modCancelarrBtnActionPerformed
        // TODO add your handling code here:
//        if(JOptionPane.showConfirmDialog(this, "Esta seguro de cancelar?", "Cancelar", JOptionPane.INFORMATION_MESSAGE) ==0){
//
//        }
        if(JOptionPane.showOptionDialog(this, "Esta seguro que quiere cancelar la edicion?", "Cancelar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,null, rootPane)==0){
            limpiarModificado();
        }

    }//GEN-LAST:event_modCancelarrBtnActionPerformed

    private void habilitarTodo(){
        modFamiliaCmb.setEnabled(true);
        modSerialTxt.setEnabled(true);
        modCodigoTxt.setEnabled(true);
        modDepositoCmb.setEnabled(true);
        jButton1.setEnabled(true);
    }
    
    private void deshabilitarTodo(){
        modFamiliaCmb.setEnabled(false);
        modSerialTxt.setEnabled(false);
        modCodigoTxt.setEnabled(false);
        modDepositoCmb.setEnabled(false);
        jButton1.setEnabled(false);
    }
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
        if (evt.getClickCount() == 2) {
            habilitarTodo();
            BusquedaEquiposTableModel model = (BusquedaEquiposTableModel) jTable1.getModel();
            Equipos item = model.getRow(jTable1.getSelectedRow());
            completarPantalla(item);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void modGuardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modGuardarBtnActionPerformed

        BusquedaEquiposTableModel model = (BusquedaEquiposTableModel) jTable1.getModel();
        Equipos itemSeleccionado = model.getRow(jTable1.getSelectedRow());
        if (itemSeleccionado != null) {
            try {
                Equipos eq = new Equipos();
                eq.setCodigo(itemSeleccionado.getCodigo());
                eq.setEqDescripcion(modNombreTxt.getText());
                if (!modSerialTxt.getText().isEmpty()) {
                    eq.setEqNroserie(modSerialTxt.getText());
                }
                if (!modObservacionTxt.getText().isEmpty()) {
                    eq.setObservaciones(modObservacionTxt.getText());
                }
                eq.setInvDepositos(((Depositos) modDepositoCmb.getSelectedItem()).getCodigo());
                eq.setInvEquiposFamilias(modFamiliaCmb.searchForeign());
                eq.setEqActivo("S");
                eq.setEqEstado(itemSeleccionado.getEqEstado());
                eq.setCodigoBarras(modCodigoTxt.getText());
                eq.setModelo(modModeloTxt.getText());
                if(!modAltoTxt.getText().isEmpty())
                    eq.setAlto(Integer.parseInt(modAltoTxt.getText()));
                if(!modAnchoTxt.getText().isEmpty())
                    eq.setAncho(Integer.parseInt(modAnchoTxt.getText()));
                if(!modLargoTxt.getText().isEmpty())
                    eq.setLargo(Integer.parseInt(modLargoTxt.getText()));
                if(!modPesoTxt.getText().isEmpty())
                    eq.setPeso(Integer.parseInt(modPesoTxt.getText()));
                
                EquiposManager.instance().update(eq);
                JOptionPane.showMessageDialog(this, "Equipo guardado con exito!", "Guardado", JOptionPane.INFORMATION_MESSAGE);
                limpiarModificado();
            } catch (RemoteException ex) {
                Logger.getLogger(ABMInventario.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Error al grabar el equipo", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un item de la grilla", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_modGuardarBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        BusquedaEquiposTableModel model = (BusquedaEquiposTableModel) jTable1.getModel();
        Equipos itemSeleccionado = model.getRow(jTable1.getSelectedRow());
        if(itemSeleccionado!=null){
            try {
                EquiposManager.instance().remove(itemSeleccionado.getCodigo());
                JOptionPane.showMessageDialog(this, "Equipo borrado con exito!", "Borrado", JOptionPane.INFORMATION_MESSAGE);
                
                
            } catch (RemoteException ex) {
                Logger.getLogger(ABMInventario.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Error al borrar el equipo", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Debe seleccionar un item de la grilla", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private String agregarCeros(String string, int largo) {
        String ceros = "";

        int cantidad = largo - string.length();

        if (cantidad >= 1) {
            for (int i = 0; i < cantidad; i++) {
                ceros += "0";
            }

            return (ceros + string);
        } else {
            return string;
        }
    }
    
    private void imprimirEtiqueta(Equipos eq){
        if (eq != null) {
            try {
                PrintService printService = PrintServiceLookup.lookupDefaultPrintService();
                
                String zplCommand2 = "^XA\n"
                        + "^FO20, 50^ADN, 11, 2^FD" + eq.getEqDescripcion() + " - " + eq.getModelo() + "^FS\n"
                        + "^FO65, 80^BY3\n"
                        + "^B3N,N,100,Y,N\n"
                        + "^FD" + agregarCeros(eq.getCodigoBarras(), 6) + "^FS\n"
                        + "^XZ";
                // convertimos el comando a bytes
                byte[] by = zplCommand2.getBytes();
                DocFlavor flavor = DocFlavor.BYTE_ARRAY.AUTOSENSE;
                Doc doc = new SimpleDoc(by, flavor, null);

                // creamos el printjob
                DocPrintJob job = printService.createPrintJob();

                // imprimimos  
                job.print(doc, null);
            } catch (PrintException ex) {
                Logger.getLogger(ABMInventario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    private void nuevoCancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoCancelarBtnActionPerformed
        
            // TODO add your handling code here:
        if(JOptionPane.showOptionDialog(this, "Esta seguro que quiere cancelar la creacion?", "Cancelar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,null, rootPane)==0){
            limpiarNuevo();
        }

    }//GEN-LAST:event_nuevoCancelarBtnActionPerformed

    private void nuevoAltoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoAltoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoAltoTxtActionPerformed

    private void nuevoAnchoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoAnchoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoAnchoTxtActionPerformed

    private void nuevoLargoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoLargoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoLargoTxtActionPerformed

    private void nuevoPesoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoPesoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoPesoTxtActionPerformed

    private void modAltoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modAltoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modAltoTxtActionPerformed

    private void modAnchoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modAnchoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modAnchoTxtActionPerformed

    private void modLargoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modLargoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modLargoTxtActionPerformed

    private void modPesoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modPesoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modPesoTxtActionPerformed

    private void modFamiliaRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modFamiliaRadActionPerformed
        // TODO add your handling code here:
        
        if(modFamiliaRad.isSelected()){
            limpiarModificado();
            modFamiliaCmb.setEnabled(true);
            modCodigoTxt.setEnabled(false);
            modNombreTxt.setEnabled(false);
            modSerialTxt.setEnabled(false);
            modDepositoCmb.setEnabled(false);
            modModeloTxt.setEnabled(false);
        }
    }//GEN-LAST:event_modFamiliaRadActionPerformed

    private void modMarcaRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modMarcaRadActionPerformed
        // TODO add your handling code here:
        if(modMarcaRad.isSelected()){
            limpiarModificado();
            modFamiliaCmb.setEnabled(false);
            modCodigoTxt.setEnabled(false);
            modNombreTxt.setEnabled(true);
            modSerialTxt.setEnabled(false);
            modDepositoCmb.setEnabled(false);
            modModeloTxt.setEnabled(true);
        }
    }//GEN-LAST:event_modMarcaRadActionPerformed

    private void modNroSerieRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modNroSerieRadActionPerformed
        // TODO add your handling code here:
        if(modNroSerieRad.isSelected()){
            limpiarModificado();
            modFamiliaCmb.setEnabled(false);
            modCodigoTxt.setEnabled(false);
            modNombreTxt.setEnabled(false);
            modSerialTxt.setEnabled(true);
            modDepositoCmb.setEnabled(false);
            modModeloTxt.setEnabled(false);
        }
    }//GEN-LAST:event_modNroSerieRadActionPerformed

    private void modCodBarraRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modCodBarraRadActionPerformed
        // TODO add your handling code here:
        if(modCodBarraRad.isSelected()){
            limpiarModificado();
            modFamiliaCmb.setEnabled(false);
            modCodigoTxt.setEnabled(true);
            modNombreTxt.setEnabled(false);
            modSerialTxt.setEnabled(false);
            modDepositoCmb.setEnabled(false);
            modModeloTxt.setEnabled(false);
        }
    }//GEN-LAST:event_modCodBarraRadActionPerformed

    private void modDepositoRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modDepositoRadActionPerformed
        // TODO add your handling code here:
        if(modDepositoRad.isSelected()){
            limpiarModificado();
            modFamiliaCmb.setEnabled(false);
            modCodigoTxt.setEnabled(false);
            modNombreTxt.setEnabled(false);
            modSerialTxt.setEnabled(false);
            modDepositoCmb.setEnabled(true);
            modModeloTxt.setEnabled(false);
        }
    }//GEN-LAST:event_modDepositoRadActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        BusquedaEquiposTableModel model = (BusquedaEquiposTableModel) jTable1.getModel();
        Equipos itemSeleccionado = model.getRow(jTable1.getSelectedRow());
        if(itemSeleccionado!=null){            
            imprimirEtiqueta(itemSeleccionado);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void modCodigoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modCodigoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modCodigoTxtActionPerformed

    private void modCodigoTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_modCodigoTxtKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            refreshTable();
        }
    }//GEN-LAST:event_modCodigoTxtKeyPressed

    private void completarPantalla(Equipos e){
        if (e.getCodigo() != null) {
            modCodigoTxt.setEnabled(false);
            modCodigoTxt.setText(e.getCodigoBarras());
            if (e.getInvDepositos() != null) {
                modDepositoCmb.setSelectedIndex(Integer.parseInt(e.getInvDepositos()));
            }
            if (e.getInvEquiposFamilias() != null) {

				modFamiliaCmb.setForeign(e.getInvEquiposFamilias());

            }
            modNombreTxt.setText(e.getEqDescripcion());
            modObservacionTxt.setText(e.getObservaciones());
            modSerialTxt.setText(e.getEqNroserie());
            modAltoTxt.setText(String.valueOf(e.getAlto()));
            modAnchoTxt.setText(String.valueOf(e.getAncho()));
            modLargoTxt.setText(String.valueOf(e.getLargo()));
            modPesoTxt.setText(String.valueOf(e.getPeso()));
            modModeloTxt.setText(e.getModelo());
        }
    }

    private void limpiarNuevo(){
        jLabel2.setForeground(Color.black);
        jLabel3.setForeground(Color.black);
        jLabel17.setForeground(Color.black);
        jLabel12.setForeground(Color.black);
        nuevoDepositoCmb.setSelectedIndex(0);
        nuevoFamiliaCmb.setSelectedIndex(0);
        nuevoNombreTxt.setText("");
        nuevoModeloTxt.setText("");
        nuevoObservacionesTxt.setText("");
        nuevoSerialTxt.setText("");
        nuevoAltoTxt.setText("");
        nuevoAnchoTxt.setText("");
        nuevoLargoTxt.setText("");
        nuevoPesoTxt.setText("");
    }

    private void limpiarModificado(){
        modCodigoTxt.setText("");
        modDepositoCmb.setSelectedIndex(0);
        modFamiliaCmb.setSelectedIndex(0);
        modNombreTxt.setText("");
        modObservacionTxt.setText("");
        modSerialTxt.setText("");
        modModeloTxt.setText("");
        modAltoTxt.setText("");
        modAnchoTxt.setText("");
        modLargoTxt.setText("");
        modPesoTxt.setText("");
        BusquedaEquiposTableModel model = (BusquedaEquiposTableModel)jTable1.getModel();
        model.clear();
        deshabilitarTodo();
        jTable1.updateUI();
    }

    private void refreshTable(){
        try {            
            ((BusquedaEquiposTableModel)jTable1.getModel()).clear();
            Equipos[] equiposEncontrados = null;
            if(modMarcaRad.isSelected())
                equiposEncontrados = EquiposManager.instance().findByField("eqDescripcion", modNombreTxt.getText());
            else if(modFamiliaRad.isSelected())
                equiposEncontrados = EquiposManager.instance().findByField("invEquiposFamilias", modFamiliaCmb.searchForeign());
            else if (modCodBarraRad.isSelected())
                equiposEncontrados = EquiposManager.instance().findByField("codigoBarras", modCodigoTxt.getText());
            else if (modDepositoRad.isSelected())
                equiposEncontrados = EquiposManager.instance().findByField("invDepositos", String.valueOf(modDepositoCmb.getSelectedIndex()));
            else if (modNroSerieRad.isSelected())
                equiposEncontrados = EquiposManager.instance().findByField("eqNroserie", modSerialTxt.getText());
            
            if (equiposEncontrados.length > 0 || equiposEncontrados == null) {
                BusquedaEquiposTableModel model = (BusquedaEquiposTableModel) jTable1.getModel();

                for (Equipos eq : equiposEncontrados) {
                    model.addRow(eq);
                }
                jTable1.setModel(model);
                jTable1.updateUI();
            }
        } catch (RemoteException ex) {
            Logger.getLogger(ABMInventario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private boolean validarNuevo(){
        boolean result = true;
        jLabel2.setForeground(Color.black);
        jLabel3.setForeground(Color.black);
        jLabel17.setForeground(Color.black);
        jLabel12.setForeground(Color.black);
        if(nuevoNombreTxt.getText().isEmpty()){
            jLabel2.setForeground(Color.red);
            result=false;
        }

        if(nuevoFamiliaCmb.getSelectedIndex()==0){
            jLabel3.setForeground(Color.red);
            result=false;
        }
        if(nuevoDepositoCmb.getSelectedIndex()==0){
            jLabel17.setForeground(Color.red);
            result=false;
        }
        if(nuevoModeloTxt.getText().isEmpty()){
            jLabel12.setForeground(Color.red);
            result=false;
        }
        return result;
    }

    private void cargarItemsComboBoxfamilias()
    {
        try {
        	modFamiliaCmb.loadItems();
            nuevoFamiliaCmb.loadItems();
            modDepositoCmb.addItem("Seleccione un deposito");
            nuevoDepositoCmb.addItem("Seleccione un deposito");
            Depositos[] depMod = DepositosManager.instance().getAll();
            if (depMod != null) {
                for (Depositos eq : depMod) {
                    modDepositoCmb.addItem(eq);
                    nuevoDepositoCmb.addItem(eq);
                }
            }

        } catch (RemoteException ex) {
            Logger.getLogger(ABMInventario.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error al cargar datos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ABMInventario dialog = new ABMInventario(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        //System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField modAltoTxt;
    private javax.swing.JTextField modAnchoTxt;
    private javax.swing.JButton modBuscarBtn;
    private javax.swing.JButton modCancelarrBtn;
    private javax.swing.JRadioButton modCodBarraRad;
    private javax.swing.JTextField modCodigoTxt;
    private javax.swing.JComboBox modDepositoCmb;
    private javax.swing.JRadioButton modDepositoRad;
    //private javax.swing.JComboBox modFamiliaCmb;
    private FamiliasComboBox modFamiliaCmb;
    private javax.swing.JRadioButton modFamiliaRad;
    private javax.swing.JButton modGuardarBtn;
    private javax.swing.JTextField modLargoTxt;
    private javax.swing.JRadioButton modMarcaRad;
    private javax.swing.JTextField modModeloTxt;
    private javax.swing.JTextField modNombreTxt;
    private javax.swing.JRadioButton modNroSerieRad;
    private javax.swing.JTextArea modObservacionTxt;
    private javax.swing.JTextField modPesoTxt;
    private javax.swing.JTextField modSerialTxt;
    private javax.swing.JTextField nuevoAltoTxt;
    private javax.swing.JTextField nuevoAnchoTxt;
    private javax.swing.JButton nuevoCancelarBtn;
    private javax.swing.JComboBox nuevoDepositoCmb;
    private FamiliasComboBox nuevoFamiliaCmb;
    private javax.swing.JButton nuevoGuardarBtn;
    private javax.swing.JTextField nuevoLargoTxt;
    private javax.swing.JTextField nuevoModeloTxt;
    private javax.swing.JTextField nuevoNombreTxt;
    private javax.swing.JTextArea nuevoObservacionesTxt;
    private javax.swing.JTextField nuevoPesoTxt;
    private javax.swing.JTextField nuevoSerialTxt;
    // End of variables declaration//GEN-END:variables

}
