/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui.gastos;

import crm.client.managers.PresupuestosManager;
import crm.client.util.DateConverter;
import gui.tables.BuscadorReportesServiciosItem;
import gui.tables.BuscadorReportesServiciosTableModel;
import gui.tables.BuscadorReportesServiciosTableRender;
import gui.tables.XLSFillter;

import java.io.File;
import java.rmi.RemoteException;
import javax.swing.JFileChooser;
import jxl.Workbook;
import jxl.write.Label;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;
import jxl.write.Number;
import jxl.write.Boolean;
import jxl.write.WritableCellFormat;
import jxl.write.WritableFont;
/**
 *
 * @author sergio
 */
public class Reportes extends javax.swing.JDialog {

    /**
     * Creates new form Reportes
     */
    public Reportes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTable1.setDefaultRenderer (Object.class, new BuscadorReportesServiciosTableRender());
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Subcontratados");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crm/gui/imagenes/page_white_excel.png"))); // NOI18N
        jButton2.setText("Exportar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Seleccione el rango de fechas a buscar");

        jDateChooser1.setDate(new java.util.Date());

        jLabel3.setText("al");

        jDateChooser2.setDate(new java.util.Date());

        jTable1.setModel(new BuscadorReportesServiciosTableModel());
        jScrollPane1.setViewportView(jTable1);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crm/gui/imagenes/cross.png"))); // NOI18N
        jButton3.setText("Cerrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crm/gui/imagenes/magnifier.png"))); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Seleccione el estado del servicio");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione...", "En OS", "Solicitado al proveedor", "Confirmado por proveedor", "A pagar", "Pagado" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Total de servicios");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1149, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jButton1))))
                                .addGap(0, 697, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(507, 507, 507))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        openSavePopUp();
    }//GEN-LAST:event_jButton2ActionPerformed

    public void openSavePopUp(){
        JFileChooser filechooser = new JFileChooser();
	    filechooser.addChoosableFileFilter(new XLSFillter());
	    filechooser.setAcceptAllFileFilterUsed(false);
		if(filechooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION){
			
			File file =filechooser.getSelectedFile();
			File f2 = new File(file.getParentFile().getPath()+"\\"+filechooser.getSelectedFile().getName()+".xls");
			
			if(filechooser.getFileFilter().accept(file))
				exportXLS(file);
			else {
				exportXLS(f2);
			}

		}
	}
    
    public static final int TYPE_STRING= 0;
	public static final int TYPE_LONG= 1;
	public static final int TYPE_INTEGER= 2;
	public static final int TYPE_DOUBLE= 3;
	public static final int TYPE_BOOLEAN= 4;
	public static final int TYPE_EVENTO= 5;
	public static final int TYPE_VENDEDOR= 6;
	private String comentariosXLS="";
	
	public void exportXLS(File file){
		int tipo=0;	
		
		          WritableWorkbook workbook;
		try {
			workbook = Workbook.createWorkbook(file);
			
			                 WritableSheet sheet = workbook.createSheet("test", 0);		
			for(int j=0;j<jTable1.getModel().getColumnCount();j++){
				Label label = new Label(j, 0,jTable1.getModel().getColumnName(j));
				sheet.addCell(label);
				if(jTable1.getModel().getColumnClass(j).equals(String.class))
					tipo=TYPE_STRING;
				else if(jTable1.getModel().getColumnClass(j).equals(Long.class))
					tipo=TYPE_LONG;
				else if(jTable1.getModel().getColumnClass(j).equals(Integer.class))
					tipo=TYPE_INTEGER;
				else if(jTable1.getModel().getColumnClass(j).equals(Double.class))
					tipo=TYPE_DOUBLE;
				else if(jTable1.getModel().getColumnClass(j).equals(java.lang.Boolean.class))
					tipo=TYPE_BOOLEAN;
				for (int i=1; i<=jTable1.getModel().getRowCount(); i++) {
					if(tipo==TYPE_STRING){
						Label labelData = new Label(j, i,(String)jTable1.getModel().getValueAt(i-1,j));
						sheet.addCell(labelData);
					}
					else if(tipo==TYPE_LONG){
						jxl.write.Number temp = new jxl.write.Number(j, i,(Long)jTable1.getModel().getValueAt(i-1,j));
						sheet.addCell(temp);
					}
					else if(tipo==TYPE_INTEGER){
                                            if(((Integer)jTable1.getModel().getValueAt(i-1,j)) != null){
						Number temp = new Number(j, i,(Integer)jTable1.getModel().getValueAt(i-1,j));
						sheet.addCell(temp);
                                            }
                                            else{
                                                Number n= new Number(j, i,0);
                                                sheet.addCell(n);
                                            }
					}
					else if(tipo==TYPE_DOUBLE){	
						//String d = (String)table.getModel().getValueAt(i-1,j);
						//Double d2 = Double.valueOf(d.substring(1,d.length()));
						
						Double d2 = (Double)jTable1.getModel().getValueAt(i-1,j);
						
						Number temp = new Number(j, i,d2);
						sheet.addCell(temp);
					}
					else if(tipo==TYPE_BOOLEAN){
						Boolean temp = new Boolean(j, i,(java.lang.Boolean)jTable1.getModel().getValueAt(i-1,j));
						sheet.addCell(temp);
					}
				}
			}
			                 WritableFont arial10font = new WritableFont(WritableFont.ARIAL, 10);
			                 WritableCellFormat arial10format = new WritableCellFormat (arial10font); 
			Label labelData = new Label(0, jTable1.getModel().getRowCount()+2,"Filtrado por: "+comentariosXLS, arial10format);			
			
			sheet.addCell(labelData);
			workbook.write();
			workbook.close();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} 
	}
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Object[] presupuestos = null;
            BuscadorReportesServiciosTableModel model = new BuscadorReportesServiciosTableModel();

            String fechaDesde = DateConverter.convertDateToString(jDateChooser1.getDate(), "yyyy-MM-dd");
            String fechaHasta = DateConverter.convertDateToString(jDateChooser2.getDate(), "yyyy-MM-dd");            
            
            presupuestos = PresupuestosManager.instance().buscarParaReportesDeServiciosSubc(fechaDesde, fechaHasta,jComboBox1.getSelectedIndex());

            double tot = 0;
            int cant = presupuestos.length;
            if (presupuestos != null) {
                for (int i = 0; i < presupuestos.length; i++) {
                    BuscadorReportesServiciosItem item = new BuscadorReportesServiciosItem();

                    Object[] p = (Object[]) presupuestos;
                    Object[] presupuestoDato = (Object[]) p[i];

                        //cant++;
                        item.setNumeroPpto((Long) (presupuestoDato[2]));
                        
                        if((String) presupuestoDato[8] != null)                        
                            item.setServicio((String) presupuestoDato[8]);
                        else
                            item.setServicio((String) presupuestoDato[12]);
                        item.setCantidad((Integer) presupuestoDato[0]);
                        item.setDias((Integer) presupuestoDato[1]);
                        
                        item.setVendedor((String) presupuestoDato[4]);
         
                        item.setNombreEvento((String) presupuestoDato[3]);
                        item.setFechaInicio((String) presupuestoDato[5]);
                        
                        item.setDescuento((Integer) presupuestoDato[7]);
                        item.setTotalServicio((Double) presupuestoDato[6]);
                        item.setProveedor((String) presupuestoDato[10]);
                        item.setEstado((Integer)presupuestoDato[9]);
                        if((Double) presupuestoDato[11] == null)
                           item.setCosto(0d);
                        else item.setCosto((Double) presupuestoDato[11]);
                        tot = tot + (Double) presupuestoDato[6];
                        model.addRow(item);
                        //jLabel3.setText("Cant. registros: " + cant);
                        //jLabel4.setText("Total: " + getTotalFormateado(tot));
                    
                }

            }
            jLabel6.setText(new Integer(cant).toString());
            jTable1.setModel(model);
            jTable1.updateUI();
            if (model.getRowCount() <= 0) {
                Util.alertMsg(this, "No se encontraron registros");
            }
        } catch (RemoteException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Reportes dialog = new Reportes(new javax.swing.JFrame(), true);
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
