/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SubcontratacionTodo.java
 *
 * Created on 02/12/2013, 09:56:44
 */

package gui.gastos;

import crm.client.managers.GastosManager;
import crm.client.managers.ProveedorManager;
import crm.libraries.abm.entities.Ppto_GastoSC;
import crm.libraries.abm.entities.Proveedor;
import java.rmi.RemoteException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import crm.client.util.Verificador;
import crm.libraries.abm.entities.Subcontratado;
import gui.tables.ServiciosSubcontratadosItem;
import gui.tables.ServiciosSubcontratadosTableModel;

import org.apache.commons.lang.StringUtils;
/**
 *
 * @author saciar
 */
public class SubcontratacionTodo extends javax.swing.JDialog {

    private ServiciosSubcontratadosTableModel model;
    private double totalFact=0.0;
    private String nroPpto;
    private String nombreSala;

    /** Creates new form SubcontratacionTodo */
    public SubcontratacionTodo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        model = new ServiciosSubcontratadosTableModel();
        loadProveedores();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jXHeader1 = new org.jdesktop.swingx.JXHeader();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Total de precio de venta de la sala completa:  $");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel4.setText("Seleccione el proveedor");

        jLabel5.setText("Costo total de la sala: $");

        jTextField1.setText("0.00");
        jTextField1.setInputVerifier(new Verificador());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crm/gui/imagenes/disk.png"))); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crm/gui/imagenes/cross.png"))); // NOI18N
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jXHeader1.setDescription("Subcontratacion");
        jXHeader1.setDescriptionFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jXHeader1.setTitle("Subcontratacion de sala completa");

        jLabel1.setText("#.##");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jXHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))
                        .addContainerGap(112, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jXHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(23, 23, 23))
        );

        setSize(new java.awt.Dimension(451, 290));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        List<ServiciosSubcontratadosItem> items = model.getRows();
        if (!StringUtils.isEmpty(jTextField1.getText())) {
            
            double costoXItem = Math.rint(Double.parseDouble(jTextField1.getText()) / items.size() * 100) / 100;
            GastosManager manager = GastosManager.instance();
            System.out.println("Costo x item = "+costoXItem);
            for (ServiciosSubcontratadosItem item : items) {
                try {                    
                    item.setCodProveedor(Long.valueOf(((Proveedor) jComboBox1.getSelectedItem()).getCodigo()));
                    item.setCosto(costoXItem);
                    if(item.getCodSubcontratado()!= null ){
                        if (!manager.grabarGastoSubcontratacion(item.getCodSubcontratado(), item.getCosto(), item.getCodProveedor(), "4")) {
                            JOptionPane.showMessageDialog(SubcontratacionTodo.this, "Ocurrio un problema durante la grabacion. Por favor vuelva a intentarlo.", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                    else {
                        Subcontratado gasto = new Subcontratado();
                        gasto.setCosto(String.valueOf(item.getCosto()));
                        gasto.setCantidad(Integer.parseInt(item.getCantidad()));
                        gasto.setPrecio(String.valueOf(item.getPrecio_vta()));
                        gasto.setDetalle("Subcontratado - " + item.getNombre());
                        
                        if(item.getCodProveedor() ==null)
                            gasto.setProveedor(null);
                        else gasto.setProveedor(String.valueOf(item.getCodProveedor()));
                        gasto.setSala(nombreSala);
                        gasto.setNroPpto(Long.parseLong(nroPpto));
                        gasto.setEstado(4);
                        manager.guardarServicioSubcontratado(gasto, item.getCodServicioPpto());                        
                    }
                    //JOptionPane.showMessageDialog(SubcontratacionTodo.this, "Se grabo la modificacion con exito.", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                } catch (RemoteException ex) {
                    Logger.getLogger(ImputacionGastosServicios.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(SubcontratacionTodo.this, "Ocurrio un problema durante la grabacion. Por favor vuelva a intentarlo.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            this.dispose();
        }
        else System.out.println("No anda babosos!!");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void loadProveedores(){
        try {
            Proveedor[] list = ProveedorManager.instance().getAllProveedores();
            for (Proveedor p : list) {
                jComboBox1.addItem(p);
            }
        } catch (RemoteException ex) {
            Logger.getLogger(ImputacionGastosServicios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private Proveedor getNombreProveedor(long cod){
        try {
            Proveedor p = ProveedorManager.instance().getProveedorById(String.valueOf(cod));
            return p;
        } catch (RemoteException ex) {
            Logger.getLogger(ImputacionGastosServicios.class.getName()).log(Level.SEVERE, null, ex);
            return null;
        }
    }

    public void loadData(String nroPpto, Long codSalaSeleccionada, String nombreSala){
        try {
            this.nroPpto=nroPpto;
            this.nombreSala=nombreSala;
            model.clear();
            GastosManager manager = GastosManager.instance();
            Object[] result = manager.getServiciosSucontratados(codSalaSeleccionada, Long.parseLong(nroPpto));
            if (result != null && result.length > 0) {
                for (int i = 0; i < result.length; i++) {
                    Object[] p = (Object[]) result[i];
                    ServiciosSubcontratadosItem item = new ServiciosSubcontratadosItem();
                    item.setCantidad((String) p[0]);
                    item.setCosto((Double) p[6]);
                    item.setDescuento((String) p[3]);
                    item.setDias((String) p[2]);                    
                    item.setPrecio_vta((Double) p[4]);
                    if((Integer)p[9]==2){//es subcontratado externo
                        item.setNombre((String) p[5]);
                    }
                    else item.setNombre((String) p[10]);

                    item.setIsSubcontratado((Integer)p[9]==2?true:false);
                    if ((Long) p[7] != null) {
                        item.setCodProveedor((Long) p[7]);
                        Proveedor provee = getNombreProveedor((Long) p[7]);
                        if (provee != null) {
                            item.setProveedor(provee);
                        }
                    }

                    item.setCodSubcontratado((Long) p[8]);
                    item.setCodServicioPpto((Long)p[11]);
                    item.setEstado((String)p[12]);
                    model.addRow(item);
                }
                jLabel3.setText(String.valueOf(totalFact));
            }
        } catch (RemoteException ex) {
            Logger.getLogger(ImputacionGastosServicios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SubcontratacionTodo dialog = new SubcontratacionTodo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private org.jdesktop.swingx.JXHeader jXHeader1;
    // End of variables declaration//GEN-END:variables

}
